#+OPTIONS: toc: nil
#+BEGIN_EXPORT html
----
title: 關於頌缽音療
author: Felix Chang
tags:
    - 音療
    - 頌缽
    - 脈輪
----

> 物質的本質是神祕的，也許，他並非如同科學家所稱的那樣客觀，也無法被化約成各種簡單的物理定律。...... 無名。
#+END_EXPORT

2015 年，我訪問了一位重症的朋友，醫學對於他的症狀可以說是完全抓不著頭緒，而求助於替代療法，而在一次偶然的機會，我訪問了他重生的經過，其中最有趣的一部分，是他分享了他的宗教經驗。

「就只要念頌**南無妙法蓮華經**，身心就莫名的被安心了下來，並經驗到一種難以形容的喜樂。而且許多生活難解的困境，冥冥中都會獲得直覺的解答。」他很認真的看著我，並邀我一同前往他們的寺院看看，當時我找不到時間，所以並沒有真的前去拜訪。

#+BEGIN_EXPORT html
<div class="video-container">
  <iframe src="https://www.youtube.com/embed/Z2cHKHGNou4" frameborder="0" allowfullscreen class="video-player"></iframe>
</div>
#+END_EXPORT

這個宗派源於日本，以念誦 「南無妙法蓮華經」為主要的修行法，整句話其實是日語，但也有可能是古漢語，這引起了我極大的興趣，因為我知道有許多的宗教中，都有持咒的修行，例如台灣的淨土宗會不斷的念頌**南無阿彌陀佛**，許多大乘佛教的宗派(包括藏傳和中國的佛教)和道教，也都會念頌六字真言「唵嘛呢叭咪吽」，東正教會念頌耶穌禱文「Lord Jesus Christ, have mercy on me」，可蘭經則是可以唱頌的。

我先把宗教的意義和對這些禱文的解釋放一旁，雖然這麼做是非常武斷與不適當的，因為，一個人所持有的信仰和知識，會直接影響一個人的感官經驗[fn:1]，但為了論述，還是做了某個程度的簡化，把注意力回到聲音的層面。

2017 年下半年，好友 Tammy 教了我一套發聲的練習，當時我被這個練習給嚇到了，因為整個練習的過程，與之前在另一名好友 Helena 的瑜伽課堂上學到的呼吸練習，竟有許多相及之處，我開始思考發聲、呼吸與身體之間的關系。幾個月後 Jeff 來到台灣，我接觸的頌缽音療，這些經驗，都讓我有許多的感受與體悟，我開始能把這許許多多的經驗給串在一起。

2018 年初，Tammy 帶來了《人聲，奇蹟的治癒力》作者伊凡‧德‧布奧恩的 CD，在 Tammy 的指導下，我們開始練起了各種的唱頌，並從中去感受聲音的共振與空間和身體的關系。

調音師

差別不在咒，在聲音，有一些聲音，會和身體的氣共振，而讓身心體驗到一種平靜和放鬆的感覺。

東正教持『主，耶穌，請憐憫我。』，在中亞的一些東正教國家裡，這句話的發音，剛好可以和心輪產生共振。這和他們的發音系統有關。這個發音，會用到喉嚨和胸腔很多的共振。
咒要要念出來，在古中亞地區，有許多的聲音，因為會和身體的氣產生共振，而被保留了下來，後來加上文化和宗教的影響，這些聲音漸漸地變成了神聖的聲音。

  「那像是日本日蓮宗所持的『南無妙法蓮華經』也是同樣的原理嗎？」我問。
  「並不一樣，例如，唵嘛呢叭咪吽，這些音，傳到中國後，已經變了，他的發
  音和原來並不一樣。」Sofia 答，而宜桔則試著念出真正的發音。「om ma ne
  beta me om」。
  「那為什麼還會有這麼多人修行，而且也會產生一些冥契的經驗？」我好奇的
  問。
  「有些是個人現象，不是每一個人都一樣，有時是文字的神聖性造成的。」
  Sofia 回答。
  是不是阿拉伯人唱頌可蘭經也是同樣的意思。」我問。
是的，因為阿拉伯文的發音，會用到許多複雜的共振。像阿拉伯這樣子的文化，他們非常的重視音，但中國的發音系統並非如此。他們認可了聲音的神聖性，這也是為何，他們常常認為，當面和一個人講一句話比寫下來來的更重要，因為這種民族『說』的特性，使得他們的語言的心靈能量很強。而這點，在中國並沒有，文字對中國來說，並聲音更重要。所以，在中東或印度，最重要的教導只能口傳，而語多沒有文字的民族，在發音上都有這個特質。發音會和氣脈共振，唱歌也是。」

  「是不是中國會比較重符也是因為對文字的重視。」我問。
  「是的。」Sofia 答。
  「那畫畫呢？」我問。
  「畫畫和觀想同一類，可以稱為有意識的觀想。」Sofia 答。

「我突然想到了，古時候的人用簡單的樂器來達到同樣的功能。例如中國以前
  有許多的鐘、鼓等。」我說。

  Sofia 說，「你有看過一些樂器產生共振嗎？只要一個產生共振，其它所有的
  都會跟著共振。」這個問題似乎幫我回答了我一直在想什麼意會對應到什麼樣
  子的脈輪這件事，Sofia 似乎看透了我的心，直接回答了另一個我沒有提問的
  問題。

* Footnotes

[fn:1] 關於感官經驗與知識信仰之間的關系，容我另作專文解釋。
